---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
library(data.table)
library(tidyverse)
library(ggpubr)
```

```{r}
data<-fread("data/area 19 and 20 march data 21-24.csv")%>%
  mutate(se.num=value*se,ymin=value-se.num,ymax=value+se.num,
         ci95=1.96*se.num,cimin=value-ci95,cimax=value+ci95)

data

```

```{r}
g1<-ggplot(data%>%filter(category=="effort"),aes(x=area,y=value,fill=factor(year)))+
  geom_col(position="dodge")+
  geom_errorbar(aes(ymin=ymin,ymax=ymax),position=position_dodge(0.9),width=0)+
  labs(y=c("boat trips"),fill="",x="",title="Effort")+
    theme(axis.text.x = element_blank(), axis.title.x = element_blank())

g2<-ggplot(data%>%filter(category=="kept"),aes(x=area,y=value,fill=factor(year)))+
  geom_col(position="dodge")+
  labs(y=c("chinook"),fill="",x="",title="Kept Chinook")+
  geom_errorbar(aes(ymin=ymin,ymax=ymax),position=position_dodge(0.9),width=0)+
  theme(axis.text.x = element_blank(), axis.title.x = element_blank())

g3<-ggplot(data%>%filter(category=="released"),aes(x=area,y=value,fill=factor(year)))+
  geom_col(position="dodge")+
  geom_errorbar(aes(ymin=ymin,ymax=ymax),position=position_dodge(0.9),width=0)+
  labs(y=c("chinook"),fill="",x="area",title="Released Chinook")

ggarrange(g1,g2,g3,ncol=1,common.legend = TRUE,legend = "bottom",align="v",heights=c(1,1,1.25))

ggsave("figures/chinook march area 19 and 20 effort kept released.png",dpi=300,units="in",height=6,width=5)

```

```{r}
g1<-ggplot(data%>%filter(category=="effort"),aes(x=area,y=value,fill=factor(year)))+
  geom_col(position="dodge")+
  geom_errorbar(aes(ymin=cimin,ymax=cimax),position=position_dodge(0.9),width=0)+
  labs(y=c("boat trips"),fill="",x="",title="Effort")+
    theme(axis.text.x = element_blank(), axis.title.x = element_blank())

g2<-ggplot(data%>%filter(category=="kept"),aes(x=area,y=value,fill=factor(year)))+
  geom_col(position="dodge")+
  labs(y=c("chinook"),fill="",x="",title="Kept Chinook")+
  geom_errorbar(aes(ymin=cimin,ymax=cimax),position=position_dodge(0.9),width=0)+
  theme(axis.text.x = element_blank(), axis.title.x = element_blank())

g3<-ggplot(data%>%filter(category=="released"),aes(x=area,y=value,fill=factor(year)))+
  geom_col(position="dodge")+
  geom_errorbar(aes(ymin=cimin,ymax=cimax),position=position_dodge(0.9),width=0)+
  labs(y=c("chinook"),fill="",x="area",title="Released Chinook")

ggarrange(g1,g2,g3,ncol=1,common.legend = TRUE,legend = "bottom",align="v",heights=c(1,1,1.25))

ggsave("figures/chinook march area 19 and 20 effort kept released with cis95.png",dpi=300,units="in",height=6,width=5)

```

```{r}
g1<-ggplot(data%>%filter(category=="effort"),aes(x=category,y=value,fill=area))+
  geom_boxplot()+
  labs(y="boat trips",x="")+
  guides(fill=FALSE)

g2<-ggplot(data%>%filter(category!="effort"),aes(x=category,y=value,fill=area))+
  geom_boxplot()+
  labs(y="number of chinook",x="")

ggarrange(g1,g2,nrow=1,align="h",widths=c(1,2),common.legend=TRUE,legend="bottom")

ggsave("figures/chinook march area 19 and 20 effort kept released boxplot.png",dpi=300,units="in",height=5,width=6)
```


