project: 
  type: website
  output-dir: docs
  render: 
    - "*.qmd"    
    - "!sbc chinook rec catch and release data summary.Rmd"
    - "!SBC-chinook-2023.Rmd"
    - "!chinook rec catch.Rmd"
    - "!creel data summary.Rmd"

website: 
  sidebar: 
    style: "docked"
    search: true
    contents:
      - text: "SBC Chinook Recreational Catch and Release Summary"
        href: sbc-chinook-rec-catch-and-release-data-summary.qmd
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left

editor: visual
  